#!/bin/bash -eu

function echoerr() { echo "$@" 1>&2; }

echoerr
echoerr 'RTAX: Rapid and accurate taxonomic classification of short paired-end'
echoerr '      sequence reads from the 16S ribosomal RNA gene.'
echoerr ''
echoerr 'David A. W. Soergel (1) and Rob Knight (2)'
echoerr ''
echoerr '1 Department of Plant and Microbial Biology,'
echoerr '  University of California, Berkeley '
echoerr '2 Howard Hughes Medical Institute and Department of Chemistry '
echoerr '  and Biochemistry, University of Colorado at Boulder'
echoerr '* Corresponding author (current address): soergel@cs.umass.edu'
echoerr ''
echoerr 'Version 0.9  (September 19, 2011)'
echoerr ''
echoerr 'http://dev.davidsoergel.com/rtax'
echoerr ''



# we want to call subsidiary scripts in the "scripts" subdir, but we don't know where we're installed or what the working directory is.
# solution from http://hintsforums.macworld.com/archive/index.php/t-73839.html

IFS=$' \t\n'
#declare -x PATH=/bin:/usr/bin:/usr/local/bin
arg=$0; [[ -L $0 ]] && arg=$(stat -f '%Y' "$0")
pth=$(2>/dev/null cd "${arg%/*}" >&2; echo "`pwd -P`/${arg##*/}")
par=$(dirname "$pth")
scripts="$par/scripts"

# Grab the command-line arguments

usageHelp="Usage: ${0##*/} -r <refdb> -t <taxonomy> -a <queryA> -b <queryB> -d <delimiter> -o <classifications.out>"
refdbHelp="-r a reference database in FASTA format"
taxonomyHelp="-t a taxonomy file with sequence IDs matching the reference database"
queryAHelp="-a a FASTA file containing query sequences (single-ended or read 1)"
queryBHelp="-b a FASTA file containing query sequences (read b, with matching IDs)"
delimiterHelp="-d A delimiter separating the two reads when provided in a single file"
outputHelp="-o the output path"
badOptionHelp="Option not recognised"
printHelpAndExit()
{
	echoerr "$usageHelp"
	echoerr "$refdbHelp"
	echoerr "$taxonomyHelp"
	echoerr "$queryAHelp"
	echoerr "$queryBHelp"
	echoerr "$delimiterHelp"
	echoerr "$outputHelp"
	exit $1
}
printErrorHelpAndExit()
{
        echoerr "-------------------------------------------------------------"
        echoerr "ERROR : $@"
        echoerr "-------------------------------------------------------------"
        echoerr
        printHelpAndExit 1
}

refdb=""
taxonomy=""
queryA=""
queryB=""
delimiter=""
verbose=""
outpath=""

while getopts "hr:t:a:b:d:o:v" optionName; do
case "$optionName" in
h) printHelpAndExit 0;;
r) refdb="$OPTARG";;
t) taxonomy="$OPTARG";;
a) queryA="$OPTARG";;
b) queryB="$OPTARG";;
d) delimiter="$OPTARG";;
o) outpath="$OPTARG";;
v) verbose="0";;
[?]) printErrorHelpAndExit "$badOptionHelp";;
esac
done



if [[ -n "$verbose" ]]
then 
echoerr
echoerr Reference database : $refdb
echoerr Taxonomy file      : $taxonomy
echoerr Query read A       : $queryA
echoerr Query read B       : $queryB
echoerr Read delimiter : $delimiter
echoerr Output path : $outpath
echoerr
fi



if [[ -z "$refdb" || -z "$taxonomy" || -z "$queryA" || -z "$outpath" ]]; then
    printErrorHelpAndExit "-r, -t, -a, and -o options are required"
fi

if [[ -n "$queryB" && -n "$delimiter" ]]; then
    printErrorHelpAndExit "Paired ends can be input using -b or -d, but not both"
fi

# find USEARCH, or hardcode if needed (could use an environment variable...)
# usearch=/path/to/usearch
set +e
usearch=`which usearch`
if [ $? -eq 0 ] 
then
    echoerr using usearch: $usearch
    echoerr
else
    echoerr "usearch not found in path.  Please correct, or just hardcode the path in the rtax script."
    exit 1
fi

set -e

# create a temporary working directory

#tempdir=/tmp/rtax.$RANDOM
tempdir=./rtax.$RANDOM
mkdir $tempdir
cd $tempdir

# perform the search


if [ $delimiter ]; then
    $scripts/splitDelimitedFasta.pl $delimiter $queryA
    queryAa=`basename $queryA`.a
    queryAb=`basename $queryA`.b
    $scripts/rtaxSearchPair.pl --database $refdb --queryA $queryAa --queryB $queryAb --usearch $usearch > rawhits
else
    if [ $queryB ]; then
        $scripts/rtaxSearchPair.pl --database $refdb --queryA $queryA --queryB $queryB --usearch $usearch > rawhits
    else
        $scripts/rtaxSearchSingle.pl --database $refdb --queryA $queryA  --usearch $usearch > rawhits
    fi
fi


# choose the "best" taxonomy assignment by walking down the tree, including info on how many ref sequences agree at each level
# and pipe directly into the cleanup scripts instead of using temp files

$scripts/rtaxVote.pl $taxonomy rawhits | $scripts/classificationQualityFilter.pl 1 0.0 0.5 | $scripts/classificationQualityStripper.pl > $outpath

# The output of this process includes the pcid-width column and a tab-delimited tax string

# filter the taxonomy strings to the finest rank where half of the hits agree (out of all the hits, i.e. including in the denominator those hits with no annotation)
#$scripts/classificationQualityFilter.pl 1 0.0 0.5 < rawtaxonomy > filteredtaxonomy

# clean up the resulting output and provide it to STDOUT
#$scripts/classificationQualityStripper.pl < filteredtaxonomy 

# remove the temp directory
# (comment out to debug or grab intermediate results)

rm -rf $tempdir